"""empty message

Revision ID: 2860a1b58306
Revises: 
Create Date: 2024-11-25 22:01:12.733618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2860a1b58306'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('tai_khoan',
        sa.Column('tai_khoan', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column('mat_khau', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column('quyen', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('tai_khoan', name='tai_khoan_pkey')
    )
    op.create_table('khachhang',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tai_khoan', sa.String(length=50), sa.ForeignKey('tai_khoan.tai_khoan'), nullable=False),
        sa.Column('mat_khau', sa.String(length=50), nullable=False),
        sa.Column('ten', sa.String(length=255), nullable=True),
        sa.Column('dia_chi', sa.String(length=255), nullable=True),
        sa.Column('sdt', sa.String(length=15), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nhanvien',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tai_khoan', sa.String(length=50), sa.ForeignKey('tai_khoan.tai_khoan'), nullable=False),
        sa.Column('mat_khau', sa.String(length=50), nullable=False),
        sa.Column('ten', sa.String(length=255), nullable=True),
        sa.Column('sdt', sa.String(length=15), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Sach',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('ten_sach', sa.String(length=255), nullable=False),
        sa.Column('mo_ta', sa.Text(), nullable=True),
        sa.Column('tac_gia', sa.String(length=255), nullable=False),
        sa.Column('nam_xuat_ban', sa.Integer(), nullable=True),
        sa.Column('trang_thai', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('themuon',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('id_khach_hang', sa.INTEGER(), sa.ForeignKey('khachhang.id'), nullable=True),
        sa.Column('id_sach_muon', sa.INTEGER(), sa.ForeignKey('Sach.id'), nullable=True),
        sa.Column('id_nhan_vien', sa.INTEGER(), sa.ForeignKey('nhanvien.id'), nullable=True),
        sa.Column('ngay_muon', sa.DATE(), nullable=True),
        sa.Column('ngay_tra_du_dinh', sa.DATE(), nullable=True),
        sa.Column('ngay_tra_thuc_te', sa.DATE(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tacgia',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('ten', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column('quoc_tich', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column('nam_sinh', sa.DATE(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    # op.drop_table('sach')
    # op.drop_table('soluongsachconlai')
    # op.drop_table('tai_khoan')
    # op.drop_table('tacgia')
    # op.drop_table('themuon')
    # op.drop_table('nhan_vien')
    # op.drop_table('khachhang')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('khachhang',
    # sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('khachhang_id_seq'::regclass)"), autoincrement=True, nullable=False),
    # sa.Column('ten', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    # sa.Column('dia_chi', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    # sa.Column('sdt', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    # sa.Column('tai_khoan', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    # sa.Column('mat_khau', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id', name='khachhang_pkey'),
    # postgresql_ignore_search_path=False
    # )
    # op.create_table('nhan_vien',
    # sa.Column('id_nhan_vien', sa.INTEGER(), server_default=sa.text("nextval('nhan_vien_id_nhan_vien_seq'::regclass)"), autoincrement=True, nullable=False),
    # sa.Column('ten', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    # sa.Column('sdt', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    # sa.Column('tai_khoan', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    # sa.Column('mat_khau', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id_nhan_vien', name='nhan_vien_pkey'),
    # postgresql_ignore_search_path=False
    # )
   
    # op.create_table('tai_khoan',
    # sa.Column('tai_khoan', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    # sa.Column('mat_khau', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    # sa.Column('quyen', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('tai_khoan', name='tai_khoan_pkey')
    # )
    # op.create_table('soluongsachconlai',
    # sa.Column('ten_sach', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    # sa.Column('tac_gia', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    # sa.Column('nam_xuat_ban', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('so_luong', sa.INTEGER(), autoincrement=False, nullable=True)
    # )
    # op.create_table('sach',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('ten_sach', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    # sa.Column('mo_ta', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('tac_gia', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    # sa.Column('nam_xuat_ban', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('trang_thai', sa.VARCHAR(length=20), server_default=sa.text("'Chưa có người mượn'::character varying"), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id', name='sach_pkey')
    # )
    op.drop_table('Sach')
    # ### end Alembic commands ###
    op.drop_table('khachhang')
    op.drop_table('nhanvien')
    op.drop_table('tai_khoan')
    op.drop_table('themuon')
    op.drop_table('tacgia')